FROM gradle:8.14.2-jdk21-alpine

WORKDIR /app

# Pre-copy Gradle wrapper & config for faster boot
COPY gradle gradle
COPY settings.gradle .

# Copy module build.gradle for caching layer
COPY buildSrc/build.gradle buildSrc/
COPY bootstrap/build.gradle bootstrap/
COPY application/build.gradle application/
COPY domain/build.gradle domain/
COPY infrastructure/build.gradle infrastructure/

# Full source for hot reload
COPY . .

# Copy start script
COPY start.sh start.sh
RUN chmod +x start.sh && ./gradlew getDependencies

# Default command
CMD ["sh", "./start.sh"]