services:
  task-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: task-service
    environment:
        - POSTGRES_DB_URL=${POSTGRES_URL}/${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - SPRING_DEVTOOLS_RESTART_ENABLED=true
    ports:
      - "8080:8080"
      - "5005:5005"
      - "35729:35729"
    volumes:
      # Chỉ map source code directories
      - ./bootstrap/src:/app/bootstrap/src:cached
      - ./application/src:/app/application/src:cached
      - ./domain/src:/app/domain/src:cached
      - ./infrastructure/src:/app/infrastructure/src:cached
      # Cache gradle dependencies
      - gradle-cache:/home/gradle/.gradle
    restart: always
    depends_on:
      - postgres
    networks:
      - task-service-db-net

  postgres:
    image: 'postgres:latest'
    container_name: task-service-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-service-db-net

volumes:
  # Named volume to persist PostgreSQL data
  postgres_data:
  gradle-cache:

networks:
  task-service-db-net:
    driver: bridge