FROM gradle:8.14.2-jdk21-alpine

WORKDIR /app

# Copy Gradle wrapper & settings
COPY gradle gradle
COPY gradlew .
COPY settings.gradle .

# Copy ALL build.gradle files
COPY build.gradle .
COPY buildSrc/ buildSrc/
COPY bootstrap/build.gradle bootstrap/
COPY application/build.gradle application/
COPY domain/build.gradle domain/
COPY infrastructure/build.gradle infrastructure/

# Copy source code vào image (sẽ được override bởi volume mount)
COPY bootstrap/src bootstrap/src
COPY application/src application/src
COPY domain/src domain/src
COPY infrastructure/src infrastructure/src

# Download dependencies
RUN ./gradlew getDependencies --no-daemon

EXPOSE 8080 5005 35729

CMD ["./gradlew", ":bootstrap:bootRun", "--no-daemon", "--continuous", "-x", "test"]

