services:
  task-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: task-service
    environment:
        - POSTGRES_DB_URL=${POSTGRES_URL}/${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - JAVA_TOOL_OPTIONS=-Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - .:/app
    command: sh ./start.sh
    restart: always
    depends_on:
      - postgres
    networks:
      - task-service-db-net

  postgres:
    image: 'postgres:latest'
    container_name: task-service-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-service-db-net

volumes:
  # Named volume to persist PostgreSQL data
  postgres_data:

networks:
  task-service-db-net:
    driver: bridge