# FROM openjdk:21-slim
FROM gradle:8.14.2-jdk21-alpine

WORKDIR /app

# Copy the Maven project files
COPY build.gradle .
COPY settings.gradle .
COPY gradle gradle
COPY bootstrap/build.gradle bootstrap/
COPY application/build.gradle application/
COPY domain/build.gradle domain/
COPY infrastructure/build.gradle infrastructure/

# Mount source code from the host (hot reload enabled)
COPY . .
